version: '3'
services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=MusiFetch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MusiFetch
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - db_network
  python:
    build:
      context: ./docker/python
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network: